### ISSUE TITLE
jmmserver tells me there's new version but download page does not list it

### ISSUE THREAD

**Issue by bond4u** [japanesemediamanager/japanesemediamanager.github.io#3]
download page lists ver 3.4.2.19

**Comment by AreFinstad** [comment]
the updates ATM is
Server:   3.4.3.2
Desktop: 3.4.3.1

the newest update had some issues with it and had to be downloaded manually, admin did send out a mass message that should be in every client (Both the JMM server and Desktop client)

here is the link for it: http://www.jmediamanager.org/jmmserver/jmmserver.all.to.3.4.3.2.zip

**Comment by bond4u** [comment]
I meant this page - http://japanesemediamanager.github.io/downloads.html

**Comment by AreFinstad** [comment]
Yes. The latest version isn't on the Site. The creator has to update it

**Comment by jmediamanager** [comment]
Yup I typically don't update that page with every release, bcoz the auto updater will take care of it.
But given the issues recently I will get this updated

**Comment by jmediamanager** [comment]
Done
