### ISSUE TITLE
Chrome flagging downloads as harmful

### ISSUE THREAD

**Issue by ShanaProject** [japanesemediamanager/japanesemediamanager.github.io#8]
Whenever I try to download any of the binaries linked to from the download page Chrome gives me a security message:

![capture](https://cloud.githubusercontent.com/assets/1846924/9575344/45281796-5012-11e5-9bcd-ee8be9425378.PNG)

The diagnostic page is: https://www.google.com/safebrowsing/diagnostic?site=http%3A%2F%2Fwww.jmediamanager.org%2Flatestdownloads%2FJMM_Server_Setup_3.4.3.2.exe.zip&client=googlechrome&hl=en-US

**Comment by AreFinstad** [comment]
yup, we are already talking about it here: https://github.com/japanesemediamanager/japanesemediamanager.github.io/pull/7#

i guess the JMM Creator does handle this once he is on. there shouldnt be any issues tho as the new code looks fair...... from what i can see

**Comment by ElementalCrisis** [comment]
I'm not positive but I would guess it's the self-extracting .EXE files JMM_Desktop_Setup_3.4.2.18.exe and JMM_Server_Setup_3.4.2.16.exe as there's been a lot of reports of Google flagging self-extracting .EXE files as malicious. Google does not like unsigned .EXE files apparently. 

https://www.virustotal.com/cs/url/94bcecb172b359ee473711d5f60f2e47d5434ec6d2c9fda9fecc3e81f94ab0f6/analysis/1441046684/

**Comment by jmediamanager** [comment]
I have submitted a request to Google to have it reviewed

**Comment by ElementalCrisis** [comment]
Just an update, japanesemediamanager.github.io is no longer flagged but jmediamanager.org still is.

**Comment by ElementalCrisis** [comment]
Final update, www.jmediamanager.org is no longer flagged, https://www.google.com/safebrowsing/diagnostic?site=www.jmediamanager.org. This topic can be closed.
